trading:
  exchange: binance
  symbols: ["BTC/USDT"]
  account_balance: 100.0
  risk_percent: 5.0
  max_exposure: 3.0

# API keys are read from environment variables:
#   FRED_API_KEY, NEWS_API_KEY, ETHERSCAN_API_KEY
