trading:
  exchange: binance
  symbols: ["BTC/USDT", "ETH/USDT"]
  account_balance: 100.0
  risk_percent: 5.0
fees:
  maker_bps: -2
  taker_bps: 10
data:
  use_websocket: true
  fallback_rest: true
  rest_rate_limit_per_min: 1200
