monitoring:
  alerts_enabled: true
  backup_enabled: true
  dashboard_enabled: true
  performance_tracking: true
risk:
  fee_rate: 0.001
  kill_switch_enabled: true
  max_daily_loss: 8.0
  max_drawdown: 0.06
  max_position: 250.0
  slippage: 0.0002
  stop_loss_pct: 0.025
trading:
  account_balance: 100.0
  exchange: binance
  live: true
  max_exposure: 2.5
  risk_percent: 3.5
  symbol: BTC/USDT
  target_balance: 1000.0
